language: python
cache: pip
python:
  - "2.7"
  - "3.5.1"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt --only-binary=numpy,scipy
  - pip install atari_py
  - pip install hacking
  - python setup.py develop
# command to run tests
script:
  - flake8 .
  - nosetests -a '!gpu' -x
  - ./test_examples.sh -1
